# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Economy_wide_MFA_EU28_2014_MAYER

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Economy_wide_MFA_EU28_2014_MAYER.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3581562,1_F_Economy_wide_MFA_EU28_2014_MAYER,"raw materials, non-metallic minerals fraction",non-metallic minerals,dry mass,EU28,2014,natural resources,"markets, processed materials",History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: DE,NaN,NaN,NaN
1,3581563,1_F_Economy_wide_MFA_EU28_2014_MAYER,"all commodities, non-metallic minerals fraction",non-metallic minerals,dry mass,EU28,2014,"import markets, global","markets, processed materials",History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: Import,NaN,NaN,NaN
2,3581564,1_F_Economy_wide_MFA_EU28_2014_MAYER,"all commodities, non-metallic minerals fraction",non-metallic minerals,dry mass,EU28,2014,"markets, processed materials","export markets, global",History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: Export,NaN,NaN,NaN
3,3581565,1_F_Economy_wide_MFA_EU28_2014_MAYER,"all commodities, non-metallic minerals fraction",non-metallic minerals,dry mass,EU28,2014,"markets, processed materials",use as energy carrier,History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: eUse,NaN,NaN,NaN
4,3581566,1_F_Economy_wide_MFA_EU28_2014_MAYER,"all commodities, non-metallic minerals fraction",non-metallic minerals,dry mass,EU28,2014,"markets, processed materials",use as material,History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: mUse,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,3581733,1_F_Economy_wide_MFA_EU28_2014_MAYER,solid and liquid waste,all materials,dry mass,EU28,2014,use as energy carrier,waste management and recycling,History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: Waste (eUse),NaN,NaN,NaN
172,3581734,1_F_Economy_wide_MFA_EU28_2014_MAYER,solid waste,all materials,dry mass,EU28,2014,waste management and recycling,"final sinks, waste",History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: DPOw,NaN,NaN,NaN
173,3581735,1_F_Economy_wide_MFA_EU28_2014_MAYER,fuel-related emissions,all materials,dry mass,EU28,2014,use as energy carrier,atmosphere,History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: DPOe,NaN,NaN,NaN
174,3581736,1_F_Economy_wide_MFA_EU28_2014_MAYER,solid waste and fuel-related emissions,all materials,dry mass,EU28,2014,entire economy,final sinks,History,...,Gg,yr,NaN,NaN,NaN,NaN,Name of original flow: DPO total (sum of emiss...,NaN,NaN,NaN
175,3581737,1_F_Economy_wide_MFA_EU28_2014_MAYER,all materials,all materials,dry mass,EU28,2014,domestic supply of resources,domestic supply of resources,History,...,Gg,yr,NaN,NaN,NaN,NaN,additionally calculated flow: Domestic supply ...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Economy_wide_MFA_EU28_2014_MAYER.xlsx','Data')
material    = 'metal ores and metals'
#material    = 'biomass'
#material    = 'fossil fuels'
#material    = 'waste, from extraction'
#material    = 'non-metallic minerals'
#material    = 'all materials (aggregate)'
material    = 'all materials'
layer       = 'dry mass'
region      = 'EU28'
scenario    = 'History'
time        = 2014

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,natural resources,"markets, processed materials","raw materials, non-metallic minerals fraction",3.071343e+06
1,"import markets, global","markets, processed materials","all commodities, non-metallic minerals fraction",7.733804e+04
2,"markets, processed materials","export markets, global","all commodities, non-metallic minerals fraction",9.851161e+04
3,"markets, processed materials",use as energy carrier,"all commodities, non-metallic minerals fraction",0.000000e+00
4,"markets, processed materials",use as material,"all commodities, non-metallic minerals fraction",3.371382e+06
...,...,...,...,...
75,use as energy carrier,waste management and recycling,solid and liquid waste,0.000000e+00
76,waste management and recycling,"final sinks, waste",solid waste,1.679978e+05
77,use as energy carrier,atmosphere,fuel-related emissions,0.000000e+00
78,entire economy,final sinks,solid waste and fuel-related emissions,1.679978e+05
79,domestic supply of resources,domestic supply of resources,all materials,1.679978e+05

In [3]:
from floweaver import *

Sankey_version = 'Economy_wide_MFA_2014_MAYER_Sankey_as_in_Paper'

# Set the default size to fit the documentation better.
size = dict(width=900, height=400)
SCALE = 2

# Define the nodes
nodes = {
    'Domestic extraction': ProcessGroup(['natural resources'], title='Domestic extraction'),
    'Imports': ProcessGroup(['import markets, global'], title='Imports'),
    'Exports': ProcessGroup(['export markets, global'], title='Exports'),
    'Materials processed': ProcessGroup(['markets, processed materials'], title='Materials processed'),
    'Material use': ProcessGroup(['use as material'], title='Material use'),
    'Stocks': ProcessGroup(['use phase'], title='Stocks'),
    'Eol_waste': ProcessGroup(['waste management and recycling'], title='Eol_waste'),
    'Energetic use': ProcessGroup(['use as energy carrier'], title='Energetic use'),
    'Domestic processed output': ProcessGroup(['final sinks, waste'], title='Domestic processed output'),
    'Atmosphere': ProcessGroup(['atmosphere'], title='Atmosphere'),    
    'Short lived products': Waypoint(title='Short lived products', direction='R'),
    'Recycling': Waypoint(title='Recycling', direction='L'),
    'R2': Waypoint(title='', direction='L'),
}

# Define the bundles
bundles = [
    Bundle('Domestic extraction', 'Materials processed'),
    Bundle('Imports', 'Materials processed'),
    Bundle('Materials processed', 'Exports'),
    Bundle('Materials processed', 'Material use'),
    Bundle('Materials processed', 'Energetic use'),
    Bundle('Material use', 'Stocks'),
    Bundle('Material use', 'Eol_waste', waypoints=['Short lived products']),
    Bundle('Stocks', 'Eol_waste'),
    Bundle('Eol_waste', 'Domestic processed output'),
    Bundle('Energetic use', 'Atmosphere'),
    Bundle('Energetic use', 'Eol_waste'),    
    Bundle('Eol_waste', 'Materials processed', waypoints=['R2','Recycling']),
]

# Define the ordering
ordering = [
[['Imports'],[],['Domestic extraction'],[],[]],
[[],[],['Materials processed'],[],['Recycling']],
[['Exports'],['Energetic use'],['Material use'],[],[]],
[[],[],['Short lived products'],['Stocks'],[]],
[[],[],[],['Eol_waste'],['R2']],
[[],['Atmosphere'],[],['Domestic processed output'],[]],
]


flows_by_type = Partition.Simple('type', ['raw materials, biomass fraction',
    'all commodities, biomass fraction',
    'recycled materials, biomass fraction',
    'solid waste, biomass fraction',
    'fuel-related emissions, biomass fraction',
    'waste, biomass fraction, from extraction',
    'solid and liquid waste, biomass fraction',
    'solid waste and fuel-related emissions, biomass fraction',
    'all materials, biomass fraction',                                          
    'raw materials, fossil fuel fraction',
    'all commodities, fossil fuel fraction',
    'recycled materials, fossil fuel fraction',
    'solid waste, fossil fuel fraction',
    'fuel-related emissions, fossil fuel fraction',
    'waste, fossil fuel fraction, from extraction',
    'solid and liquid waste, fossil fuel fraction',
    'solid waste and fuel-related emissions, fossil fuel fraction',
    'all materials, fossil fuel fraction',                                          
    'raw materials, metal ores and metals fraction',
    'all commodities, metal ores and metals fraction',
    'recycled materials, metal ores and metals fraction',
    'solid waste, metal ores and metals fraction',
    'fuel-related emissions, metal ores and metals fraction',
    'waste, metal ores and metals fraction, from extraction',
    'solid and liquid waste, metal ores and metals fraction',
    'solid waste and fuel-related emissions, metal ores and metals fraction',
    'all materials, metal ores and metals fraction',
    'raw materials',
    'all commodities',
    'recycled materials',
    'solid waste',
    'fuel-related emissions',
    'waste, from extraction',
    'raw materials, waste from extraction',    
    'solid and liquid waste',
    'solid waste and fuel-related emissions',
    'all materials',                                          
    'raw materials, non-metallic minerals fraction',
    'all commodities, non-metallic minerals fraction',
    'recycled materials, non-metallic minerals fraction',
    'solid waste, non-metallic minerals fraction',
    'fuel-related emissions, non-metallic minerals fraction',
    'waste, non-metallic minerals fraction, from extraction',   
    'solid and liquid waste, non-metallic minerals fraction',
    'solid waste and fuel-related emissions, non-metallic minerals fraction',
    'all materials, non-metallic minerals fraction',                                          
])

# Define the color palette
palette = {
    'raw materials, biomass fraction': 'forestgreen',
    'all commodities, biomass fraction': 'forestgreen',
    'recycled materials, biomass fraction': 'forestgreen',
    'solid waste, biomass fraction': 'forestgreen',
    'fuel-related emissions, biomass fraction': 'forestgreen',
    'waste, biomass fraction, from extraction': 'forestgreen',
    'solid and liquid waste, biomass fraction': 'forestgreen',
    'solid waste and fuel-related emissions, biomass fraction': 'forestgreen',
    'all materials, biomass fraction': 'forestgreen',        
    'raw materials, fossil fuel fraction': 'yellow',
    'all commodities, fossil fuel fraction': 'yellow',
    'recycled materials, fossil fuel fraction': 'yellow',
    'solid waste, fossil fuel fraction': 'yellow',
    'fuel-related emissions, fossil fuel fraction': 'yellow',
    'waste, fossil fuel fraction, from extraction': 'yellow',
    'solid and liquid waste, fossil fuel fraction': 'yellow',
    'solid waste and fuel-related emissions, fossil fuel fraction': 'yellow',
    'all materials, fossil fuel fraction': 'yellow',       
    'raw materials, metal ores and metals fraction': 'mediumblue',
    'all commodities, metal ores and metals fraction': 'mediumblue',
    'recycled materials, metal ores and metals fraction': 'mediumblue',
    'solid waste, metal ores and metals fraction': 'mediumblue',
    'fuel-related emissions, metal ores and metals fraction': 'mediumblue',
    'waste, metal ores and metals fraction, from extraction': 'mediumblue',
    'solid and liquid waste, metal ores and metals fraction': 'mediumblue',
    'solid waste and fuel-related emissions, metal ores and metals fraction': 'mediumblue',
    'all materials, metal ores and metals fraction': 'mediumblue',
    'raw materials': 'navy',
    'all commodities': 'navy',
    'recycled materials': 'navy',
    'solid waste': 'navy',
    'fuel-related emissions': 'navy',
    'waste, from extraction': 'slategray',
    'raw materials, waste from extraction': 'slategray',
    'solid and liquid waste': 'slategray',
    'solid waste and fuel-related emissions': 'slategray',
    'all materials': 'navy',     
    'raw materials, non-metallic minerals fraction': 'darkorange',
    'all commodities, non-metallic minerals fraction': 'darkorange',
    'recycled materials, non-metallic minerals fraction': 'darkorange',
    'solid waste, non-metallic minerals fraction': 'darkorange',
    'fuel-related emissions, non-metallic minerals fraction': 'darkorange',
    'waste, non-metallic minerals fraction, from extraction': 'darkorange',   
    'solid and liquid waste, non-metallic minerals fraction': 'darkorange',
    'solid waste and fuel-related emissions, non-metallic minerals fraction': 'darkorange',
    'all materials, non-metallic minerals fraction': 'darkorange',        
}

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, 
                       flow_partition=flows_by_type)

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)
Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")