# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_China_Sand_Gravel_MFA_2050_Scenario_REN

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_China_Sand_Gravel_MFA_2050_Scenario_REN.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3580954,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,sand and gravel,"construction minerals, related materials and w...",dry mass,China,2050,mining - natural sand and gravel,building and construction,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
1,3580955,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,crushed stone,"construction minerals, related materials and w...",dry mass,China,2050,mining - crushed stone,building and construction,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
2,3580956,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,recycled aggregates,"construction minerals, related materials and w...",dry mass,China,2050,market for recycled materials,building and construction,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
3,3580957,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,aggregates,"construction minerals, related materials and w...",dry mass,China,2050,building and construction,use phase - buildings,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
4,3580958,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,aggregates,"construction minerals, related materials and w...",dry mass,China,2050,building and construction,use phase - infrastructure,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
5,3580959,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, construction, mineralic, non-metallic","construction minerals, related materials and w...",dry mass,China,2050,building and construction,waste management,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
6,3580960,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - buildings, mineralic, non-...","construction minerals, related materials and w...",dry mass,China,2050,use phase - buildings,waste management,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
7,3580961,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - infrastructure, mineralic,...","construction minerals, related materials and w...",dry mass,China,2050,use phase - infrastructure,waste management,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
8,3580962,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - buildings, mineralic, non-...","construction minerals, related materials and w...",dry mass,China,2050,waste management,recycling - aggregates,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
9,3580963,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - infrastructure, mineralic,...","construction minerals, related materials and w...",dry mass,China,2050,waste management,recycling - aggregates,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
10,3580964,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, construction, mineralic, non-metallic","construction minerals, related materials and w...",dry mass,China,2050,waste management,recycling - aggregates,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
11,3580965,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - buildings, mineralic, non-...","construction minerals, related materials and w...",dry mass,China,2050,waste management,building and construction - use of fillings,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
12,3580966,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - infrastructure, mineralic,...","construction minerals, related materials and w...",dry mass,China,2050,waste management,building and construction - use of fillings,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
13,3580967,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, construction, mineralic, non-metallic","construction minerals, related materials and w...",dry mass,China,2050,waste management,building and construction - use of fillings,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
14,3580968,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - buildings, mineralic, non-...","construction minerals, related materials and w...",dry mass,China,2050,waste management,landfilling,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
15,3580969,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, demolition - infrastructure, mineralic,...","construction minerals, related materials and w...",dry mass,China,2050,waste management,landfilling,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
16,3580970,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,"waste, construction, mineralic, non-metallic","construction minerals, related materials and w...",dry mass,China,2050,waste management,landfilling,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
17,3580971,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,recycled aggregates from demolished buildings,"construction minerals, related materials and w...",dry mass,China,2050,recycling - aggregates,market for recycled materials,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
18,3580972,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,recycled aggregates from demolished infrastruc...,"construction minerals, related materials and w...",dry mass,China,2050,recycling - aggregates,market for recycled materials,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN
19,3580973,1_F_China_Sand_Gravel_MFA_2050_Scenario_REN,recycled aggregates from construction waste,"construction minerals, related materials and w...",dry mass,China,2050,recycling - aggregates,market for recycled materials,all measures,...,Pg,yr,NaN,NaN,NaN,NaN,"""all measures"" includes more intense building ...",NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_China_Sand_Gravel_MFA_2050_Scenario_REN.xlsx','Data')
material    = 'construction minerals, related materials and waste'
layer       = 'dry mass'
region      = 'China'
scenario    = 'all measures'
time        = 2050

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,mining - natural sand and gravel,building and construction,sand and gravel,1.306000
1,mining - crushed stone,building and construction,crushed stone,3.606764
2,market for recycled materials,building and construction,recycled aggregates,4.453681
3,building and construction,use phase - buildings,aggregates,5.534722
4,building and construction,use phase - infrastructure,aggregates,3.648067
5,building and construction,waste management,"waste, construction, mineralic, non-metallic",0.183656
6,use phase - buildings,waste management,"waste, demolition - buildings, mineralic, non-...",6.050964
7,use phase - infrastructure,waste management,"waste, demolition - infrastructure, mineralic,...",3.547522
8,waste management,recycling - aggregates,"waste, demolition - buildings, mineralic, non-...",2.322264
9,waste management,recycling - aggregates,"waste, demolition - infrastructure, mineralic,...",2.057955
10,waste management,recycling - aggregates,"waste, construction, mineralic, non-metallic",0.073462
11,waste management,building and construction - use of fillings,"waste, demolition - buildings, mineralic, non-...",1.647596
12,waste management,building and construction - use of fillings,"waste, demolition - infrastructure, mineralic,...",0.653410
13,waste management,building and construction - use of fillings,"waste, construction, mineralic, non-metallic",0.088155
14,waste management,landfilling,"waste, demolition - buildings, mineralic, non-...",2.081105
15,waste management,landfilling,"waste, demolition - infrastructure, mineralic,...",0.836157
16,waste management,landfilling,"waste, construction, mineralic, non-metallic",0.022039
17,recycling - aggregates,market for recycled materials,recycled aggregates from demolished buildings,2.322264
18,recycling - aggregates,market for recycled materials,recycled aggregates from demolished infrastruc...,2.057955
19,recycling - aggregates,market for recycled materials,recycled aggregates from construction waste,0.073462

In [3]:
import pandas as pd
from floweaver import *

Sankey_version = 'China_Sand_Gravel_REN_Sankey_as_in_Paper'

# Set the default size to fit the documentation better.
size = dict(width=900, height=400)
SCALE = 7.0

nodes = {
    'sources':    ProcessGroup(['mining - natural sand and gravel',
                                'mining - crushed stone',
                                'market for recycled materials']),
    'construction sector': ProcessGroup(['building and construction']),
    'final_use' : ProcessGroup(['use phase - buildings',
                                'use phase - infrastructure']),
    'waste management' : ProcessGroup(['waste management']),
    'finalsink' : ProcessGroup(['landfilling',
                                'building and construction - use of fillings',
                                'recycling - aggregates']),
    'recycled aggregates'      : Waypoint(direction='L')}


ordering = [
    ['sources'],       # put "sources" on the left...
    ['construction sector'],
    ['final_use','recycled aggregates'],
    ['waste management'],
    ['finalsink'],   # ... and "finalsink" on the right.
]


bundles = [
    Bundle('sources',    'construction sector'),
    Bundle('construction sector', 'final_use'),
    Bundle('final_use',  'waste management'),
    Bundle('construction sector', 'waste management'),    
    Bundle('waste management',  'finalsink'),
    Bundle('finalsink', 'sources', waypoints=['recycled aggregates'])]


nodes['sources'].partition   = Partition.Simple('process', ['mining - natural sand and gravel',
                                                            'mining - crushed stone',
                                                            'market for recycled materials'])
nodes['final_use'].partition = Partition.Simple('process', ['use phase - buildings', 'use phase - infrastructure'])
nodes['finalsink'].partition = Partition.Simple('process', ['landfilling',
                                                            'building and construction - use of fillings',
                                                            'recycling - aggregates'])


# Partition by the "type/commodity" column of the flows table
flows_by_type = Partition.Simple('type', ['waste, construction, mineralic, non-metallic', 'recycled aggregates', 
                                          'waste, demolition - buildings, mineralic, non-metallic',
                                          'waste, demolition - infrastructure, mineralic, non-metallic',
                                          'recycled aggregates from construction waste',
                                          'recycled aggregates from demolished buildings',
                                          'recycled aggregates from demolished infrastructure',
                                          'aggregates', 'sand and gravel', 'crushed stone'])

# Set the colours for the labels in the partition.
palette = {'waste, construction, mineralic, non-metallic': 'greenyellow','recycled aggregates': 'yellow',
           'recycled aggregates from construction waste': 'greenyellow',
           'aggregates': 'purple', 'sand and gravel': 'chocolate', 'crushed stone': 'orange',
           'waste, demolition - buildings, mineralic, non-metallic': 'darkgreen',
           'waste, demolition - infrastructure, mineralic, non-metallic':'limegreen',
           'recycled aggregates from demolished buildings': 'darkgreen',
           'recycled aggregates from demolished infrastructure':'limegreen'}

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, 
                       flow_partition=flows_by_type)

# w1 = weave(sdd, flows, palette=palette).to_widget(**size).auto_save_png('sand_example_v1.png')
Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)
Sankey.scale = SCALE

#Sankey # Show below
Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")

In [6]:
import pandas as pd
from floweaver import *

Sankey_version = 'China_Sand_Gravel_REN_materials_aggregated'

# Set the default size to fit the documentation better.
size = dict(width=900, height=400)
SCALE = 7.0

nodes = {
    'sources':    ProcessGroup(['mining - natural sand and gravel',
                                'mining - crushed stone',
                                'market for recycled materials']),
    'construction sector': ProcessGroup(['building and construction']),
    'final_use' : ProcessGroup(['use phase - buildings',
                                'use phase - infrastructure']),
    'waste management' : ProcessGroup(['waste management']),
    'finalsink' : ProcessGroup(['landfilling',
                                'building and construction - use of fillings',
                                'recycling - aggregates']),
    'recycled aggregates'      : Waypoint(direction='L')}


ordering = [
    ['sources'],       # put "sources" on the left...
    ['construction sector'],
    ['final_use','recycled aggregates'],
    ['waste management'],
    ['finalsink'],   # ... and "finalsink" on the right.
]


bundles = [
    Bundle('sources',    'construction sector'),
    Bundle('construction sector', 'final_use'),
    Bundle('final_use',  'waste management'),
    Bundle('construction sector', 'waste management'),    
    Bundle('waste management',  'finalsink'),
    Bundle('finalsink', 'sources', waypoints=['recycled aggregates'])]


nodes['sources'].partition   = Partition.Simple('process', ['mining - natural sand and gravel',
                                                            'mining - crushed stone',
                                                            'market for recycled materials'])
nodes['final_use'].partition = Partition.Simple('process', ['use phase - buildings', 'use phase - infrastructure'])
nodes['finalsink'].partition = Partition.Simple('process', ['landfilling',
                                                            'building and construction - use of fillings',
                                                            'recycling - aggregates'])


# Partition by the "type/commodity" column of the flows table
flows_by_type = Partition.Simple('type', ['aggregates', 'sand and gravel', 'crushed stone',
                                          ('construction waste', ['waste, construction, mineralic, non-metallic', 
                                          'waste, demolition - buildings, mineralic, non-metallic',
                                          'waste, demolition - infrastructure, mineralic, non-metallic']),
                                          ('recycled material', ['recycled aggregates', 'recycled aggregates from construction waste',
                                          'recycled aggregates from demolished buildings',
                                          'recycled aggregates from demolished infrastructure'])])

# Set the colours for the labels in the partition.
palette = {'construction waste': 'limegreen',
           'recycled material': 'darkgreen',
           'aggregates': 'purple', 'sand and gravel': 'chocolate', 'crushed stone': 'orange'}

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, 
                       flow_partition=flows_by_type)

# w1 = weave(sdd, flows, palette=palette).to_widget(**size).auto_save_png('sand_example_v1.png')
Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

#Sankey # Show below
Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [7]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [8]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")