# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Economy_wide_MFA_Global_EU27_2005_HAAS

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Economy_wide_MFA_Global_EU27_2005_HAAS.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3581276,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"raw materials, biomass fraction",biomass,dry mass,EU27,2005,natural resources,"markets, processed materials",History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: DE,NaN,NaN,NaN
1,3581277,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"all commodities, biomass fraction",biomass,dry mass,EU27,2005,"markets, global","markets, processed materials",History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: PTB,NaN,NaN,NaN
2,3581278,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"all commodities, biomass fraction",biomass,dry mass,EU27,2005,"markets, processed materials",use as energy carrier,History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Energetic use,NaN,NaN,NaN
3,3581279,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"all commodities, biomass fraction",biomass,dry mass,EU27,2005,"markets, processed materials",use as material,History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Material use,NaN,NaN,NaN
4,3581280,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"all commodities, biomass fraction",biomass,dry mass,EU27,2005,use as material,use phase,History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Addition to stocks,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,3581557,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"all commodities, construction minerals fraction",all materials,dry mass,Global,2005,use as material,waste management and recycling,History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Short lived products,NaN,NaN,NaN
282,3581558,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"recycled materials, construction minerals frac...",all materials,dry mass,Global,2005,waste management and recycling,"markets, processed materials",History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Recycling,NaN,NaN,NaN
283,3581559,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"solid waste, construction minerals fraction",all materials,dry mass,Global,2005,waste management and recycling,final sinks,History,...,Pg,yr,NaN,NaN,NaN,NaN,Name of original flow: Waste,NaN,NaN,NaN
284,3581560,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"fuel-related emissions, construction minerals ...",all materials,dry mass,Global,2005,use as energy carrier,final sinks,History,...,Pg,yr,NaN,NaN,NaN,NaN,additionally calculated flow: DPOe (domestic p...,NaN,NaN,NaN
285,3581561,1_F_Economy_wide_MFA_Global_EU27_2005_HAAS,"waste, construction minerals fraction, from ex...",all materials,dry mass,Global,2005,"markets, processed materials",final sinks,History,...,Pg,yr,NaN,NaN,NaN,NaN,additionally calculated flow: waste rock = DE ...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Economy_wide_MFA_Global_EU27_2005_HAAS.xlsx','Data')
#material    = 'metal ores and metals'
#material    = 'biomass'
#material    = 'fossil fuels'
#material    = 'waste, from extraction'
#material    = 'industrial minerals'
#material    = 'construction minerals'
#material    = 'all materials (aggregate)'
material    = 'all materials'
layer       = 'dry mass'
region      = 'EU27'
#region      = 'Global'
scenario    = 'History'
time        = 2005
Title       = '1_F_Economy_wide_MFA_Global_EU27_2005_HAAS_' + region + '_' + str(time)

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,natural resources,"markets, processed materials","raw materials, biomass fraction",1.939685
1,"markets, global","markets, processed materials","all commodities, biomass fraction",0.068408
2,"markets, processed materials",use as energy carrier,"all commodities, biomass fraction",1.591230
3,"markets, processed materials",use as material,"all commodities, biomass fraction",0.568225
4,use as material,use phase,"all commodities, biomass fraction",0.212084
...,...,...,...,...
61,use as material,waste management and recycling,"all commodities, construction minerals fraction",0.149114
62,waste management and recycling,"markets, processed materials","recycled materials, construction minerals frac...",0.699736
63,waste management and recycling,final sinks,"solid waste, construction minerals fraction",0.821430
64,use as energy carrier,final sinks,"fuel-related emissions, construction minerals ...",0.000000
65,"markets, processed materials",final sinks,"waste, construction minerals fraction, from ex...",0.000000

In [3]:
from floweaver import *

Sankey_version = 'Economy_wide_MFA_2005_HAAS_Sankey_as_in_Paper'

# Set the default size to fit the documentation better.
size = dict(width=900, height=400)
SCALE = 2

# Define the nodes
nodes = {
    'Domestic extraction': ProcessGroup(['natural resources'], title='Domestic extraction'),
    'Net imports': ProcessGroup(['markets, global'], title='Net imports'),
    'Materials processed': ProcessGroup(['markets, processed materials'], title='Materials processed'),
    'Material use': ProcessGroup(['use as material'], title='Material use'),
    'Stocks': ProcessGroup(['use phase'], title='Stocks'),
    'Eol_waste': ProcessGroup(['waste management and recycling'], title='Eol_waste'),
    'Energetic use': ProcessGroup(['use as energy carrier'], title='Energetic use'),
    'Domestic processed output': ProcessGroup(['final sinks'], title='Domestic processed output'),
    'Waste rock': Waypoint(title='Waste rock', direction='R'),
    'Short lived products': Waypoint(title='Short lived products', direction='R'),
    'Recycling': Waypoint(title='Recycling', direction='L'),
    'R2': Waypoint(title='', direction='L'),
}

# Define the bundles
bundles = [
    Bundle('Domestic extraction', 'Materials processed'),
    Bundle('Net imports', 'Materials processed'),
    Bundle('Materials processed', 'Material use'),
    Bundle('Materials processed', 'Energetic use'),
    Bundle('Material use', 'Stocks'),
    Bundle('Material use', 'Eol_waste', waypoints=['Short lived products']),
    Bundle('Stocks', 'Eol_waste'),
    Bundle('Eol_waste', 'Domestic processed output'),
    Bundle('Energetic use', 'Domestic processed output'),
    Bundle('Materials processed', 'Domestic processed output', waypoints=['Waste rock']),
    Bundle('Eol_waste', 'Materials processed', waypoints=['R2','Recycling']),
]

# Define the ordering
ordering = [
[[],['Net imports'],[],['Domestic extraction'],[]],
[[],[],[],['Materials processed'],['Recycling']],
[['Energetic use'],[],[],['Material use'],[]],
[[],['Waste rock'],['Short lived products'],['Stocks'],[]],
[[],[],[],['Eol_waste'],['R2']],
[[],[],[],['Domestic processed output'],[]],
]


flows_by_type = Partition.Simple('type', ['raw materials, biomass fraction',
    'all commodities, biomass fraction',
    'recycled materials, biomass fraction',
    'solid waste, biomass fraction',
    'fuel-related emissions, biomass fraction',
    'waste, biomass fraction, from extraction',
    'raw materials, fossil fuel fraction',
    'all commodities, fossil fuel fraction',
    'recycled materials, fossil fuel fraction',
    'solid waste, fossil fuel fraction',
    'fuel-related emissions, fossil fuel fraction',
    'waste, fossil fuel fraction, from extraction',
    'raw materials, metal ores and metals fraction',
    'all commodities, metal ores and metals fraction',
    'recycled materials, metal ores and metals fraction',
    'solid waste, metal ores and metals fraction',
    'fuel-related emissions, metal ores and metals fraction',
    'waste, metal ores and metals fraction, from extraction',
    'raw materials',
    'all commodities',
    'recycled materials',
    'solid waste',
    'fuel-related emissions',
    'waste, from extraction',
    'raw materials, waste from extraction',                                     
    'raw materials, industrial minerals fraction',
    'all commodities, industrial minerals fraction',
    'recycled materials, industrial minerals fraction',
    'solid waste, industrial minerals fraction',
    'fuel-related emissions, industrial minerals fraction',
    'waste, industrial minerals fraction, from extraction',
    'raw materials, construction minerals fraction',
    'all commodities, construction minerals fraction',
    'recycled materials, construction minerals fraction',
    'solid waste, construction minerals fraction',
    'fuel-related emissions, construction minerals fraction',
    'waste, construction minerals fraction, from extraction',                                          
])

# Define the color palette
palette = {
    'raw materials, biomass fraction': 'forestgreen',
    'all commodities, biomass fraction': 'forestgreen',
    'recycled materials, biomass fraction': 'forestgreen',
    'solid waste, biomass fraction': 'forestgreen',
    'fuel-related emissions, biomass fraction': 'forestgreen',
    'waste, biomass fraction, from extraction': 'forestgreen',
    'raw materials, fossil fuel fraction': 'yellow',
    'all commodities, fossil fuel fraction': 'yellow',
    'recycled materials, fossil fuel fraction': 'yellow',
    'solid waste, fossil fuel fraction': 'yellow',
    'fuel-related emissions, fossil fuel fraction': 'yellow',
    'waste, fossil fuel fraction, from extraction': 'yellow',
    'raw materials, metal ores and metals fraction': 'mediumblue',
    'all commodities, metal ores and metals fraction': 'mediumblue',
    'recycled materials, metal ores and metals fraction': 'mediumblue',
    'solid waste, metal ores and metals fraction': 'mediumblue',
    'fuel-related emissions, metal ores and metals fraction': 'mediumblue',
    'waste, metal ores and metals fraction, from extraction': 'mediumblue',
    'raw materials': 'navy',
    'all commodities': 'navy',
    'recycled materials': 'navy',
    'solid waste': 'navy',
    'fuel-related emissions': 'navy',
    'waste, from extraction': 'slategray',
    'raw materials, waste from extraction': 'slategray',
    'raw materials, industrial minerals fraction': 'tomato',
    'all commodities, industrial minerals fraction': 'tomato',
    'recycled materials, industrial minerals fraction': 'tomato',
    'solid waste, industrial minerals fraction': 'tomato',
    'fuel-related emissions, industrial minerals fraction': 'tomato',
    'waste, industrial minerals fraction, from extraction': 'tomato',
    'raw materials, construction minerals fraction': 'darkorange',
    'all commodities, construction minerals fraction': 'darkorange',
    'recycled materials, construction minerals fraction': 'darkorange',
    'solid waste, construction minerals fraction': 'darkorange',
    'fuel-related emissions, construction minerals fraction': 'darkorange',
    'waste, construction minerals fraction, from extraction': 'darkorange',    
}

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, 
                       flow_partition=flows_by_type)

# w1 = weave(sdd, flows, palette=palette).to_widget(**size).auto_save_png('sand_example_v1.png')
Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)
#Sankey.scale = SCALE

#Sankey # Show below
Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")