## Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_paper_pulp_EU_2012_2021_JRC

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_paper_pulp_EU_2012_2021_JRC.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3855516,1_F_paper_pulp_EU_2012_2021_JRC,pulp,pulp and paper,dry mass,Germany,2012,pulp industry,market for paper pulp,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
1,3855517,1_F_paper_pulp_EU_2012_2021_JRC,pulp,pulp and paper,dry mass,Germany,2012,import of pulp,market for paper pulp,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
2,3855518,1_F_paper_pulp_EU_2012_2021_JRC,pulp,pulp and paper,dry mass,Germany,2012,market for paper pulp,export of pulp,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
3,3855519,1_F_paper_pulp_EU_2012_2021_JRC,pulp,pulp and paper,dry mass,Germany,2012,market for paper pulp,manufacturing of paper and paper products,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
4,3855520,1_F_paper_pulp_EU_2012_2021_JRC,recovered paper,pulp and paper,dry mass,Germany,2012,market for recovered paper,manufacturing of paper and paper products,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,3859831,1_F_paper_pulp_EU_2012_2021_JRC,recovered paper,pulp and paper,dry mass,Slovakia,2021,market for recovered paper,export of recovered paper,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
4316,3859832,1_F_paper_pulp_EU_2012_2021_JRC,recovered pulp,pulp and paper,dry mass,Slovakia,2021,market for recovered paper,export of recovered pulp,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
4317,3859833,1_F_paper_pulp_EU_2012_2021_JRC,recovered paper,pulp and paper,dry mass,Slovakia,2021,import of recovered paper,market for recovered paper,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
4318,3859834,1_F_paper_pulp_EU_2012_2021_JRC,recovered pulp,pulp and paper,dry mass,Slovakia,2021,import of recoverd pulp,market for paper pulp,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN
4319,3859835,1_F_paper_pulp_EU_2012_2021_JRC,paper and paperboard,pulp and paper,dry mass,Slovakia,2021,market for and use of paper and paper products,unaccounted loss,History,...,km3_SWE,yr,NaN,NaN,NaN,NaN,Unit km3_SWE stands for thousand cubic meters ...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_paper_pulp_EU_2012_2021_JRC.xlsx','Data')
material    = 'pulp and paper'
layer       = 'dry mass'
region      = 'Czechia'
#region      = 'Greece'
#region      = 'Denmark'
region      = 'Sweden'
#region      = 'Germany'
#region      = 'Austria'
#region      = 'Belgium'
#region      = 'Cyprus'

scenario    = 'History'
time        =  2018

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,market for and use of paper and paper products,export of paper and paperboard,paper and paperboard,13608
1,market for and use of paper and paper products,market for recovered paper,recovered paper,49
2,market for paper by-products,market for recovered paper,paper by-products,1765
3,manufacturing of paper and paper products,market for and use of paper and paper products,paper and paperboard,15909
4,manufacturing of paper and paper products,market for paper by-products,paper by-products,1765
5,import of paper and paperboard,market for and use of paper and paper products,paper and paperboard,0
6,market for paper pulp,manufacturing of paper and paper products,pulp,19789
7,market for paper pulp,export of pulp,pulp,6038
8,import of pulp,market for paper pulp,pulp,0
9,pulp industry,market for paper pulp,pulp,25818
10,market for recovered paper,manufacturing of paper and paper products,recovered paper,0
11,market for recovered paper,export of recovered paper,recovered paper,0
12,market for recovered paper,export of recovered pulp,recovered pulp,0
13,import of recovered paper,market for recovered paper,recovered paper,428
14,import of recoverd pulp,market for paper pulp,recovered pulp,9
15,market for and use of paper and paper products,unaccounted loss,paper and paperboard,2252

In [3]:
from floweaver import *

Sankey_version = '1_F_paper_pulp_EU_2012_2021_JRC'

# Define the nodes
nodes = {
    'pulp industry': ProcessGroup(['pulp industry'], title='pulp industry'),
    'import of pulp': ProcessGroup(['import of pulp'], title='import of pulp'),
    'export of pulp': ProcessGroup(['export of pulp'], title='exports'),
    'market for paper pulp': ProcessGroup(['market for paper pulp'], title='market for paper pulp'),
    'import of recoverd pulp': ProcessGroup(['import of recoverd pulp'], title='import of recoverd pulp'),
    'market for recovered paper': ProcessGroup(['market for recovered paper'], title='market for recovered paper'),
    'import of paper and paperboard': ProcessGroup(['import of paper and paperboard'], title='paper imports'),
    'market for paper by-products': ProcessGroup(['market for paper by-products'], title='market for paper by-products'),
    'manufacturing of paper and paper products': ProcessGroup(['manufacturing of paper and paper products'], title='paper production'),  
    'market for and use of paper and paper products': ProcessGroup(['market for and use of paper and paper products'], title='market for and use of paper and paper products'),  
    'export of paper and paperboard': ProcessGroup(['export of paper and paperboard'], title='paper exports'),
    'unaccounted loss': ProcessGroup(['unaccounted loss'], title='unaccounted loss'),
    'export of recovered pulp': ProcessGroup(['export of recovered pulp'], title='export of recovered pulp'),
    'import of recovered paper': ProcessGroup(['import of recovered paper'], title='import of recovered paper'),
    'export of recovered paper': ProcessGroup(['export of recovered paper'], title='export of recovered paper'),
    'loop1': Waypoint(title='', direction='L'),   
}

# Define the bundles
bundles = [
    Bundle('pulp industry', 'market for paper pulp'),
    Bundle('import of pulp', 'market for paper pulp'),
    Bundle('import of recoverd pulp', 'market for paper pulp'),    
    Bundle('market for paper pulp','export of pulp'),    
    Bundle('market for paper pulp','manufacturing of paper and paper products'),
    Bundle('market for recovered paper', 'manufacturing of paper and paper products', waypoints=['loop1']),
    Bundle('manufacturing of paper and paper products', 'market for and use of paper and paper products'),
    Bundle('manufacturing of paper and paper products', 'market for paper by-products'),
    Bundle('market for paper by-products', 'market for recovered paper'),
    Bundle('import of paper and paperboard','market for and use of paper and paper products'),
    Bundle('market for and use of paper and paper products', 'market for recovered paper'),
    Bundle('market for and use of paper and paper products', 'unaccounted loss'),
    Bundle('market for and use of paper and paper products', 'export of paper and paperboard'),
    Bundle('import of recovered paper', 'market for recovered paper'), 
    Bundle('market for recovered paper','export of recovered pulp'),
    Bundle('market for recovered paper','export of recovered paper'),
]

# Define the ordering
ordering = [
[['import of pulp'],['pulp industry'],['import of recoverd pulp'],[],[]],
[[],['market for paper pulp'],[],[],[]],
[['import of paper and paperboard'],['manufacturing of paper and paper products'],[],[],['export of pulp']],
[[],['market for and use of paper and paper products'],['market for paper by-products'],[],[]],
[['import of recovered paper'],[],['unaccounted loss'],[],['export of paper and paperboard']],
[[],['market for recovered paper'],[],['loop1'],[]],
[[],[],['export of recovered pulp'],['export of recovered paper'],[],],
]

palette = {
    'pulp':                 'lightgrey',
    'recovered paper':      'wheat',
    'recovered pulp':       'lightgrey',
    'paper and paperboard': 'tan',
    'paper by-products':    'lightblue',
    'unaccounted loss':     'peachpuff',
}

# Generate the Sankey diagram
size = dict(width=1400, height=400)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=Partition.Simple('type', list(palette.keys())))

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")