## Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Wood_Products_Trade_Balance_Germany_1996_2025_Thuenen

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Wood_Products_Trade_Balance_Germany_1996_2025_Thuenen.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3684885,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,roundwood,"wood, wood waste, and wood products",dry mass,Germany,1996,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
1,3684886,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,roundwood,"wood, wood waste, and wood products",dry mass,Germany,1996,domestic market for wood and all wood products...,"markets, global",History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
2,3684887,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,wood residues and waste wood,"wood, wood waste, and wood products",dry mass,Germany,1996,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
3,3684888,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,wood residues and waste wood,"wood, wood waste, and wood products",dry mass,Germany,1996,domestic market for wood and all wood products...,"markets, global",History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
4,3684889,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,sawnwood,"wood, wood waste, and wood products",dry mass,Germany,1996,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,3685600,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,paper products,"wood, wood waste, and wood products",dry mass,Germany,2025,domestic market for wood and all wood products...,"markets, global",History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
716,3685601,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,printed matter and recorded media,"wood, wood waste, and wood products",dry mass,Germany,2025,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
717,3685602,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,printed matter and recorded media,"wood, wood waste, and wood products",dry mass,Germany,2025,domestic market for wood and all wood products...,"markets, global",History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
718,3685603,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,regenerated cellulose and artificial filaments,"wood, wood waste, and wood products",dry mass,Germany,2025,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
719,3685604,1_F_Wood_Products_Trade_Balance_Germany_1996_2...,regenerated cellulose and artificial filaments,"wood, wood waste, and wood products",dry mass,Germany,2025,domestic market for wood and all wood products...,"markets, global",History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Wood_Products_Trade_Balance_Germany_1996_2025_Thuenen.xlsx','Data')
material    = 'wood, wood waste, and wood products'
layer       = 'dry mass'
region      = 'Germany'
scenario    = 'History'
time        =  2025

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,roundwood,4.517756
1,domestic market for wood and all wood products...,"markets, global",roundwood,6.333905
2,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,wood residues and waste wood,1.451020
3,domestic market for wood and all wood products...,"markets, global",wood residues and waste wood,2.806004
4,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,sawnwood,5.859793
5,domestic market for wood and all wood products...,"markets, global",sawnwood,13.440934
6,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,wood panels,7.428522
7,domestic market for wood and all wood products...,"markets, global",wood panels,5.614761
8,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,"wood products, semi-finished",1.567584
9,domestic market for wood and all wood products...,"markets, global","wood products, semi-finished",1.088811
10,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,pulp,14.454524
11,domestic market for wood and all wood products...,"markets, global",pulp,5.640379
12,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,recovered paper,16.897705
13,domestic market for wood and all wood products...,"markets, global",recovered paper,5.102441
14,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,paper and paperboard,31.231023
15,domestic market for wood and all wood products...,"markets, global",paper and paperboard,47.657371
16,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,wood products,22.086885
17,domestic market for wood and all wood products...,"markets, global",wood products,12.929675
18,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,paper products,10.185538
19,domestic market for wood and all wood products...,"markets, global",paper products,13.328058
20,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,printed matter and recorded media,1.724307
21,domestic market for wood and all wood products...,"markets, global",printed matter and recorded media,1.585075
22,"market for wood and all wood products, aggregated",domestic market for wood and all wood products...,regenerated cellulose and artificial filaments,0.655662
23,domestic market for wood and all wood products...,"markets, global",regenerated cellulose and artificial filaments,1.217913

In [3]:
from floweaver import *

Sankey_version = '1_F_Wood_Products_Trade_Balance_Germany_1996_2025_Thuenen.xlsx'

# Define the nodes
nodes = {
    'market for wood and all wood products, aggregated': ProcessGroup(['market for wood and all wood products, aggregated'], title='aggregated market'),
    'domestic market for wood and all wood products, aggregated': ProcessGroup(['domestic market for wood and all wood products, aggregated'], title='domestic market for wood and all wood products, aggregated'),
    'markets, global': ProcessGroup(['markets, global'], title='markets, global'),
}
# Define the bundles
bundles = [
    Bundle('market for wood and all wood products, aggregated', 'domestic market for wood and all wood products, aggregated'),
    Bundle('domestic market for wood and all wood products, aggregated', 'markets, global'),
]

# Define the ordering
ordering = [
[['market for wood and all wood products, aggregated']],
[['domestic market for wood and all wood products, aggregated']],
[['markets, global']],
]

flows_by_type = Partition.Simple('type', [
    'roundwood','wood residues and waste wood','sawnwood',
    'wood panels', 'pulp', 'recovered paper', 'paper and paperboard',
    'wood products', 'paper products', 'wood products, semi-finished', 'printed matter and recorded media','regenerated cellulose and artificial filaments',
])

palette = {
    'roundwood':                                          'olivedrab',
    'wood residues and waste wood':                       'olivedrab',
    'sawnwood':                                           'sandybrown',
    'wood panels':                                        'sandybrown',
    'pulp':                                               'cornflowerblue',
    'recovered paper':                                    'cornflowerblue',
    'paper and paperboard':                               'lightgrey',
    'wood products':                                      'mediumpurple',
    'paper products':                                     'lightgrey',
    'wood products, semi-finished':                       'sandybrown',
    'printed matter and recorded media':                  'lightgrey',
    'regenerated cellulose and artificial filaments':     'cornflowerblue',
}

# Generate the Sankey diagram
size = dict(width=1000, height=200)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")