# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Watari_2025_SteelSankeys_30Regions

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Watari_2025_SteelSankeys_30Regions.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3581738,1_F_Watari_2025_SteelSankeys_30Regions,iron ore,iron,mass,China,2000,mining,market for iron ore,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3581739,1_F_Watari_2025_SteelSankeys_30Regions,iron ore,iron,mass,China,2000,market for iron ore,DRI production,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3581740,1_F_Watari_2025_SteelSankeys_30Regions,iron ore,iron,mass,China,2000,market for iron ore,production of pig iron,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3581741,1_F_Watari_2025_SteelSankeys_30Regions,losses,iron,mass,China,2000,production of pig iron,losses,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3581742,1_F_Watari_2025_SteelSankeys_30Regions,pig iron,iron,mass,China,2000,production of pig iron,BOF,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21940,3603678,1_F_Watari_2025_SteelSankeys_30Regions,reference,iron,mass,Australia,2019,reference flow start,reference flow end,History,...,Gg,yr,NaN,NaN,NaN,NaN,This is the reference flow for the legend of t...,NaN,NaN,NaN
21941,3603679,1_F_Watari_2025_SteelSankeys_30Regions,reference,iron,mass,South Africa,2019,reference flow start,reference flow end,History,...,Gg,yr,NaN,NaN,NaN,NaN,This is the reference flow for the legend of t...,NaN,NaN,NaN
21942,3603680,1_F_Watari_2025_SteelSankeys_30Regions,reference,iron,mass,Malaysia,2019,reference flow start,reference flow end,History,...,Gg,yr,NaN,NaN,NaN,NaN,This is the reference flow for the legend of t...,NaN,NaN,NaN
21943,3603681,1_F_Watari_2025_SteelSankeys_30Regions,reference,iron,mass,Thailand,2019,reference flow start,reference flow end,History,...,Gg,yr,NaN,NaN,NaN,NaN,This is the reference flow for the legend of t...,NaN,NaN,NaN
21944,3603682,1_F_Watari_2025_SteelSankeys_30Regions,reference,iron,mass,Sweden,2019,reference flow start,reference flow end,History,...,Gg,yr,NaN,NaN,NaN,NaN,This is the reference flow for the legend of t...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Watari_2025_SteelSankeys_30Regions.xlsx','Data')
material    = 'iron'
layer       = 'mass'
region      = 'Sweden'
scenario    = 'History'
time        =  2010

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,mining,market for iron ore,iron ore,17400.000000
1,market for iron ore,export of iron ore,iron ore,12491.238671
2,market for iron ore,export of iron ore,balancing item,1516.817081
3,market for iron ore,production of pig iron,iron ore,3278.066821
4,market for iron ore,DRI production,iron ore,113.877428
5,production of pig iron,losses,losses,20.651821
6,production of pig iron,BOF,pig iron,2782.447761
7,production of pig iron,export of pig iron,pig iron,137.970000
8,production of pig iron,EAF,pig iron,392.752239
9,DRI production,losses,losses,0.717428
10,DRI production,EAF,directly reduced iron (DRI),101.200000
11,DRI production,export of direct reduced iron,directly reduced iron (DRI),11.960000
12,market for steel scrap,export of steel scrap,"steel scrap, for recycling",1286.740000
13,market for steel scrap,losses,losses,348.707221
14,market for steel scrap,EAF,"steel scrap, for recycling",1059.506486
15,market for steel scrap,BOF,"steel scrap, for recycling",695.611940
16,BOF,losses,losses,215.639701
17,BOF,production of ingots and semis,"steel, from basic oxygen furnace (BOF)",3262.420000
18,EAF,losses,losses,66.798725
19,EAF,production of ingots and semis,"steel, from electric arc furnace (EAF)",1486.660000
20,production of ingots and semis,production of long products,steel ingots and semis,1032.438769
21,production of ingots and semis,production of flat products,steel ingots and semis,3657.841231
22,production of ingots and semis,export of ingots and semis,steel ingots and semis,228.340000
23,production of long products,export of long products,"steel, long products",565.460000
24,production of long products,production of final products and commodities,"steel, long products",1119.160000
25,production of long products,market for steel scrap,"steel scrap, for recycling",167.098769
26,production of flat products,production of final products and commodities,"steel, flat products",2503.304751
27,production of flat products,market for steel scrap,"steel scrap, for recycling",592.016480
28,production of flat products,export of flat products,"steel, flat products",2559.760000
29,production of final products and commodities,export of final products and commodities,final products and commodities,2170.210000
30,production of final products and commodities,use phase,final products and commodities,3452.635686
31,production of final products and commodities,market for steel scrap,"steel scrap, for recycling",417.612265
32,import of final products and commodities,production of final products and commodities,final products and commodities,2417.993200
33,import of pig iron,production of pig iron,pig iron,55.755000
34,import of steel scrap,market for steel scrap,"steel scrap, for recycling",220.500000
35,import of ingots and semis,production of ingots and semis,steel ingots and semis,169.540000
36,import of long products,production of long products,"steel, long products",819.280000
37,import of flat products,production of flat products,"steel, flat products",1997.240000
38,use phase,market for steel scrap,"steel scrap, for recycling",1993.338134
39,reference flow start,reference flow end,reference,30000.000000

In [3]:
from floweaver import *

Sankey_version = 'Watari_2025_SteelSankeys_30Regions_Sankey_as_in_Paper'

# Define the nodes
nodes = {
    'mining': ProcessGroup(['mining'], title='Mine'),
    'market for iron ore': ProcessGroup(['market for iron ore'], title='Iron ore'),
    'market for steel scrap': ProcessGroup(['market for steel scrap'], title='Scrap steel'),
    'imports of ore and scrap': ProcessGroup(['import of iron ore', 'import of steel scrap'], title='Imports'),
    'exports of ore and scrap': ProcessGroup(['export of iron ore', 'export of steel scrap'], title='Exports'),
    'production of pig iron': ProcessGroup(['production of pig iron'], title='Pig iron production'),
    'DRI production': ProcessGroup(['DRI production'], title='Direct reduced iron'),
    'imports of pig and DRI': ProcessGroup(['import of pig iron', 'import of direct reduced iron'], title='Imports'),
    'exports of pig and DRI': ProcessGroup(['export of pig iron', 'export of direct reduced iron'], title='Exports'),
    'BOF': ProcessGroup(['BOF'], title='BOF steel'),
    'EAF': ProcessGroup(['EAF'], title='EAF steel'),
    'production of ingots and semis': ProcessGroup(['production of ingots and semis'], title='Ingots and semis'),
    'imports of ingots and semis': ProcessGroup(['import of ingots and semis'], title='Imports'),
    'exports of ingots and semis': ProcessGroup(['export of ingots and semis'], title='Exports'),
    'production of long products': ProcessGroup(['production of long products'], title='Long products'),
    'production of flat products': ProcessGroup(['production of flat products'], title='Flat products'),
    'imports of long and flat': ProcessGroup(['import of long products', 'import of flat products'], title='Imports'),
    'exports of long and flat': ProcessGroup(['export of long products', 'export of flat products'], title='Exports'),
    'production of final products and commodities': ProcessGroup(['production of final products and commodities'], title='End-use goods'),
    'import of final products and commodities': ProcessGroup(['import of final products and commodities'], title='Imports'),
    'export of final products and commodities': ProcessGroup(['export of final products and commodities'], title='Exports'),
    'use phase': ProcessGroup(['use phase'], Partition.Simple('type', []), title='Stock'),
    'losses': ProcessGroup(['losses'], title='Loss'),
    'loss_way1': Waypoint(title='', direction='R'),
    'loss_way2': Waypoint(title='', direction='R'),
    'scrap_way1': Waypoint(title='', direction='L'),
    'scrap_way2': Waypoint(title='', direction='L'),
    'scrap_way3': Waypoint(title='', direction='L'),
    'reference flow start': ProcessGroup(['reference flow start'], title='30 Mt'),
    'reference flow end': ProcessGroup(['reference flow end'], title=' ')
}


# Define the bundles
bundles = [
    Bundle('mining', 'market for iron ore'),
    Bundle('imports of ore and scrap', 'market for iron ore'),
    Bundle('market for iron ore', 'production of pig iron'),
    Bundle('market for iron ore', 'DRI production'),
    Bundle('market for iron ore', 'exports of ore and scrap'),
    Bundle('imports of ore and scrap', 'market for steel scrap'),
    Bundle('market for steel scrap', 'exports of ore and scrap'),
    Bundle('market for steel scrap', 'BOF'),
    Bundle('market for steel scrap', 'EAF'),
    Bundle('imports of pig and DRI', 'production of pig iron'),
    Bundle('production of pig iron', 'exports of pig and DRI'),
    Bundle('production of pig iron', 'BOF'),
    Bundle('production of pig iron', 'EAF'),
    Bundle('imports of pig and DRI', 'DRI production'),
    Bundle('DRI production', 'exports of pig and DRI'),
    Bundle('DRI production', 'EAF'),
    Bundle('BOF', 'production of ingots and semis'),
    Bundle('EAF', 'production of ingots and semis'),
    Bundle('imports of ingots and semis', 'production of ingots and semis'),
    Bundle('production of ingots and semis', 'exports of ingots and semis'),
    Bundle('production of ingots and semis', 'production of long products'),
    Bundle('production of ingots and semis', 'production of flat products'),
    Bundle('imports of long and flat', 'production of long products'),
    Bundle('production of long products', 'exports of long and flat'),
    Bundle('imports of long and flat', 'production of flat products'),
    Bundle('production of flat products', 'exports of long and flat'),
    Bundle('production of long products', 'production of final products and commodities'),
    Bundle('production of flat products', 'production of final products and commodities'),
    Bundle('import of final products and commodities', 'production of final products and commodities'),
    Bundle('production of final products and commodities', 'export of final products and commodities'),
    Bundle('production of final products and commodities', 'use phase'),
    Bundle('market for steel scrap', 'losses', waypoints=['loss_way1', 'loss_way2']),
    Bundle('production of pig iron', 'losses', waypoints=['loss_way2']),
    Bundle('DRI production', 'losses', waypoints=['loss_way2']),
    Bundle('BOF', 'losses'),
    Bundle('EAF', 'losses'),
    Bundle('production of long products', 'market for steel scrap', waypoints=['scrap_way1']),
    Bundle('production of flat products', 'market for steel scrap', waypoints=['scrap_way1']),
    Bundle('production of final products and commodities', 'market for steel scrap', waypoints=['scrap_way2', 'scrap_way1']),
    Bundle('use phase', 'market for steel scrap', waypoints=['scrap_way3', 'scrap_way2', 'scrap_way1']),
    Bundle('reference flow start', 'reference flow end'),
]

# Define the ordering
ordering = [
[['imports of ore and scrap'],['mining'], [],[],['reference flow start']],
[['imports of pig and DRI'],['market for iron ore', 'market for steel scrap'],[],[],['reference flow end']],
[[],['production of pig iron','DRI production'],['loss_way1'],[],['exports of ore and scrap']],
[['imports of ingots and semis'],['BOF','EAF'],['loss_way2'],[],['exports of pig and DRI']],
[['imports of long and flat'],['production of ingots and semis'],['losses'],[],[]],
[['import of final products and commodities'],['production of long products','production of flat products'],[],['scrap_way1'],['exports of ingots and semis']],
[[],['production of final products and commodities'],[],['scrap_way2'],[ 'exports of long and flat']],
[[],['use phase'],[],['scrap_way3'],['export of final products and commodities']],
]

flows_by_type = Partition.Simple('type', ['iron ore','losses','pig iron','directly reduced iron (DRI)',
                                            'steel, from basic oxygen furnace (BOF)','steel, from electric arc furnace (EAF)',
                                            'steel ingots and semis','steel, long products','steel scrap, for recycling',
                                            'steel, flat products','final products and commodities','balancing item','reference',])

# Define the color palette
palette = {
    'iron ore': '#525252',
    'pig iron': '#0868ac',
    'directly reduced iron (DRI)': '#4eb3d3',
    'steel, from basic oxygen furnace (BOF)': '#2b8cbe',
    'steel, from electric arc furnace (EAF)': '#7bccc4',
    'steel ingots and semis': '#a8ddb5',
    'steel, long products': '#ccebc5',
    'steel, flat products': '#e0f3db',
    'final products and commodities': '#dfc27d',
    'losses': '#f0f0f0',
    'steel scrap, for recycling': '#d9d9d9',
    'balancing item': '#fb6a4a',
    'reference': '#d9d9d9',
}

# Generate the Sankey diagram
size = dict(width=1100, height=400)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")