## Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Roundwood_Balance_Germany_2000_2025_Thuenen

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Roundwood_Balance_Germany_2000_2025_Thuenen.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3684121,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2000,forestry,market for roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
1,3684122,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2000,import of roundwood,market for roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
2,3684123,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2000,stock decrease,market for roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
3,3684124,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2000,market for roundwood,domestic consumption,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
4,3684125,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2000,market for roundwood,export of roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,3684272,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2025,import of roundwood,market for roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
152,3684273,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2025,stock decrease,market for roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
153,3684274,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2025,market for roundwood,domestic consumption,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
154,3684275,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2025,market for roundwood,export of roundwood,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
155,3684276,1_F_Roundwood_Balance_Germany_2000_2025_Thuenen,roundwood,wood,dry mass,Germany,2025,market for roundwood,stock increase,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Roundwood_Balance_Germany_2000_2025_Thuenen.xlsx','Data')
material    = 'wood'
layer       = 'dry mass'
region      = 'Germany'
scenario    = 'History'
time        =  2001

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

                 source                target       type      value
0              forestry  market for roundwood  roundwood  56.167724
1   import of roundwood  market for roundwood  roundwood   3.587168
2        stock decrease  market for roundwood  roundwood   2.387846
3  market for roundwood  domestic consumption  roundwood  57.169136
4  market for roundwood   export of roundwood  roundwood   4.973602
5  market for roundwood        stock increase  roundwood   0.000000

In [3]:
from floweaver import *

Sankey_version = '1_F_Roundwood_Balance_Germany_2000_2025_Thuenen'

# Define the nodes
nodes = {
    'forestry': ProcessGroup(['forestry'], title='forestry'),
    'import of roundwood': ProcessGroup(['import of roundwood'], title='imports'),
    'stock decrease': ProcessGroup(['stock decrease'], title='stock decrease'),
    'market for roundwood': ProcessGroup(['market for roundwood'], title='market for roundwood'),
    'export of roundwood': ProcessGroup(['export of roundwood'], title='exports'),
    'domestic consumption': ProcessGroup(['domestic consumption'], title='domestic consumption'),
    'stock increase': ProcessGroup(['stock increase'], title='stock increase'),
}
# Define the bundles
bundles = [
    Bundle('forestry', 'market for roundwood'),
    Bundle('import of roundwood', 'market for roundwood'),
    Bundle('stock decrease', 'market for roundwood'),
    Bundle('market for roundwood', 'export of roundwood'),
    Bundle('market for roundwood', 'domestic consumption'),
    Bundle('market for roundwood', 'stock increase'),
]

# Define the ordering
ordering = [
[['import of roundwood'],['forestry'],['stock decrease']],
[[],['market for roundwood']],
[[],['domestic consumption'],[],['stock increase'],['export of roundwood']],
]

flows_by_type = Partition.Simple('type', ['roundwood'])

palette = {
    'roundwood':            'olivedrab',
}

# Generate the Sankey diagram
size = dict(width=600, height=200)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")