# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Concrete_Materials_Sankey_2018_CAO_2026

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Concrete_Materials_Sankey_2018_CAO_2026.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3662181,1_F_Concrete_Materials_Sankey_2018_CAO_2026,raw meal,concrete materials,dry mass,Global,2018,raw meal production,cement clinker production,History,...,Pg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3662182,1_F_Concrete_Materials_Sankey_2018_CAO_2026,oxygen,concrete materials,dry mass,Global,2018,oxygen supply,cement clinker production,History,...,Pg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3662183,1_F_Concrete_Materials_Sankey_2018_CAO_2026,carbon dioxide,concrete materials,dry mass,Global,2018,cement clinker production,atmosphere,History,...,Pg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3662184,1_F_Concrete_Materials_Sankey_2018_CAO_2026,cement clinker,concrete materials,dry mass,Global,2018,cement clinker production,cement production,History,...,Pg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3662185,1_F_Concrete_Materials_Sankey_2018_CAO_2026,cement kiln dust,concrete materials,dry mass,Global,2018,cement clinker production,"waste management, industrial waste",History,...,Pg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,3662624,1_F_Concrete_Materials_Sankey_2018_CAO_2026,mortar,concrete materials,dry mass,East and Southeast Asia and Developing Pacific,2018,mixing of mortar,use phase - buildings and infrastructure,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,3662625,1_F_Concrete_Materials_Sankey_2018_CAO_2026,construction and demolition waste,concrete materials,dry mass,East and Southeast Asia and Developing Pacific,2018,use phase - buildings and infrastructure,"waste management, C&D waste",History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445,3662626,1_F_Concrete_Materials_Sankey_2018_CAO_2026,construction and demolition waste,concrete materials,dry mass,East and Southeast Asia and Developing Pacific,2018,"waste management, C&D waste",aggregates production,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446,3662627,1_F_Concrete_Materials_Sankey_2018_CAO_2026,construction and demolition waste,concrete materials,dry mass,East and Southeast Asia and Developing Pacific,2018,"waste management, C&D waste",landfilling,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
447,3662628,1_F_Concrete_Materials_Sankey_2018_CAO_2026,other materials,concrete materials,dry mass,East and Southeast Asia and Developing Pacific,2018,cement clinker production,balancing items,History,...,Gg,yr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Concrete_Materials_Sankey_2018_CAO_2026.xlsx','Data')
material    = 'concrete materials'
layer       = 'dry mass'
region      = 'France'
region      = 'Africa'
region      = 'Global'
scenario    = 'History'
time        = 2018
Title       = '11_F_Concrete_Materials_Sankey_2018_CAO_2026_' + region + '_' + str(time)

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,raw meal production,cement clinker production,raw meal,5.41000
1,oxygen supply,cement clinker production,oxygen,1.28000
2,cement clinker production,atmosphere,carbon dioxide,1.77000
3,cement clinker production,cement production,cement clinker,3.28000
4,cement clinker production,"waste management, industrial waste",cement kiln dust,0.20000
5,fly ash supply,cement production,fly ash,0.12000
6,gypsum production,cement production,gypsum,0.16000
7,limestone production,cement production,limestone,0.26000
8,other material supply,cement production,other materials,0.05000
9,puzzolana production,cement production,puzzolana,0.03000
10,slag production,cement production,slag,0.21000
11,import of cement,cement production,cement,0.16000
12,cement production,export of cement,cement,0.17000
13,cement production,mixing of cement binder,cement,4.10000
14,fly ash supply,mixing of cement binder,fly ash,0.08000
15,slag production,mixing of cement binder,slag,0.02000
16,import of cement binder,mixing of cement binder,cement binder,0.00217
17,mixing of cement binder,export of cement binder,cement binder,0.00389
18,mixing of cement binder,mixing of concrete,cement binder,2.67000
19,aggregates production,mixing of concrete,aggregates,11.47000
20,water supply,mixing of concrete,water,1.20000
21,mixing of cement binder,mixing of mortar,cement binder,1.46000
22,aggregates production,mixing of mortar,aggregates,3.87000
23,water supply,mixing of mortar,water,0.72000
24,mixing of concrete,"waste management, C&D waste",production waste,0.28000
25,mixing of mortar,"waste management, C&D waste",production waste,0.11000
26,mixing of concrete,use phase - buildings and infrastructure,concrete,15.06000
27,mixing of mortar,use phase - buildings and infrastructure,mortar,5.94000
28,use phase - buildings and infrastructure,"waste management, C&D waste",construction and demolition waste,3.79000
29,"waste management, C&D waste",aggregates production,construction and demolition waste,0.03000
30,"waste management, C&D waste",landfilling,construction and demolition waste,4.18000
31,cement clinker production,balancing items,other materials,1.44000

In [3]:
import floweaver
from floweaver import *
from matplotlib import rcParams

Sankey_version = 'Concrete_Materials_2018_CAO_Sankey_as_in_Paper'

# Set the default size to fit the documentation better.
size = dict(width=900, height=400)
SCALE = 2

print("floweaver version:", floweaver.__version__)

rcParams.update({
    "font.family": 'Arial',  
    "font.size": 25,         
    
    "pdf.fonttype": 42,      # TrueType fonts, editable in Illustrator
    "ps.fonttype": 42,
    "svg.fonttype": "none",  # keep text as text in SVG
})

# Define the nodes
nodes = {
    'Raw meal': ProcessGroup(['raw meal production'], title='Raw meal'),
    'O2': ProcessGroup(['oxygen supply'], title='Oxygen'),
    'Puzzolana': ProcessGroup(['puzzolana production'], title='Puzzolana'),
    'Gypsum': ProcessGroup(['gypsum production'], title='Gypsum'),
    'Limestone': ProcessGroup(['limestone production'], title='Limestone'),
    'Fly ash': ProcessGroup(['fly ash supply'], title='Fly ash'),
    'Slag': ProcessGroup(['slag production'], title='Slag'),
    'Others': ProcessGroup(['other material supply'], title='Others'),
    'Water': ProcessGroup(['water supply']),
    'Aggregates': ProcessGroup(['aggregates production']),
    
    'Clinker production': ProcessGroup(['cement clinker production'], title='Clinker'),
    'Cement consumption': ProcessGroup(['cement production'], title='Cement'),
    'Cement binder': ProcessGroup(['mixing of cement binder'], title='Binder'),
    
    'Cement import': ProcessGroup(['import of cement'], title='Imports'),
    'Cement export': ProcessGroup(['export of cement'], title='Exports'),
    'Cement product import': ProcessGroup(['import of cement binder'], title='Imports'),
    'Cement product export': ProcessGroup(['export of cement binder'], title='Exports'),
    
    'Concrete': ProcessGroup(['mixing of concrete']),
    'Mortar': ProcessGroup(['mixing of mortar']),

    'Waste': ProcessGroup(['waste management, C&D waste']),
    'Landfill': ProcessGroup(['landfilling']),
    
    'CO2': ProcessGroup(['atmosphere'], title='CO\u2082'),
    'CKD': ProcessGroup(['waste management, industrial waste'], title='CKD'),
    'Balance': ProcessGroup(['balancing items'], title='Balance'),
    
    'Stock': ProcessGroup(['use phase - buildings and infrastructure']),
    
    'Admixture preparation': Waypoint(title='', direction='R'),

    # 占位符 / placeholder
    'empty1': ProcessGroup(['empty1'], title=''),
}

# Define the bundles
bundles = [
    Bundle('Raw meal', 'Clinker production'),
    Bundle('O2', 'Clinker production'),
    Bundle('Clinker production', 'CKD'),
    Bundle('Clinker production', 'CO2'),
    Bundle('Clinker production', 'Balance'),
    Bundle('Clinker production', 'Cement consumption'),
    Bundle('Cement import', 'Cement consumption'),
    Bundle('Puzzolana', 'Cement consumption'),
    Bundle('Gypsum', 'Cement consumption'),
    Bundle('Limestone', 'Cement consumption'),
    Bundle('Others', 'Cement consumption'),
    Bundle('Fly ash', 'Cement consumption', waypoints=['Admixture preparation']),
    Bundle('Slag', 'Cement consumption', waypoints=['Admixture preparation']),
    Bundle('Cement consumption', 'Cement export'),
    Bundle('Cement consumption', 'Cement binder'),
    Bundle('Fly ash', 'Cement binder'),
    Bundle('Slag', 'Cement binder'),
    Bundle('Cement product import', 'Cement binder'),
    Bundle('Cement binder', 'Concrete'),
    Bundle('Cement binder', 'Mortar'),
    Bundle('Cement binder', 'Cement product export'),
    Bundle('Water', 'Concrete'),
    Bundle('Water', 'Mortar',),
    Bundle('Aggregates', 'Concrete',),
    Bundle('Aggregates', 'Mortar'),
    Bundle('Concrete', 'Stock'),
    Bundle('Mortar', 'Stock'),
    Bundle('Concrete', 'Waste'),
    Bundle('Mortar', 'Waste'),
    Bundle('Stock', 'Waste'),
    Bundle('Waste', 'Landfill'),
    Bundle('Waste', 'Aggregates'),
    Bundle('Clinker production', 'empty1'),    
]

# Define the ordering
ordering = [
    [[],                       ['Raw meal','O2','Puzzolana','Gypsum','Limestone','Others','Fly ash','Slag','Water','Aggregates'],[]],
    [['Cement import'],        ['Clinker production','Admixture preparation'],                                                   []],
    [['Cement product import'],['Cement consumption','CKD','CO2','Balance',],                                                    []],
    [['Cement export'],        ['Cement binder'],                                                                                []],
    [['Cement product export'],['Concrete','Mortar'],                                                                            []],
    [[],                       ['Stock','empty1'],                                                                               []],
    [[],                       ['Waste','empty1'],                                                                               []], 
    [[],                       ['Landfill','empty1'],                                                                            []],
]

# Define the color palette
palette = {
    'puzzolana': "#c3c0c0",
    'gypsum': '#c3c0c0',
    'limestone': '#c3c0c0',
    'other materials': '#c3c0c0',
    'fly ash': '#c3c0c0',
    'slag': '#c3c0c0',
    'oxygen': "#8C8C8C",

    'aggregates': "#E0E0E0",
    'water': "#8CC8CB",

    'raw meal': "#5F5D60",
    'cement clinker': "#79787a",
    'cement': "#0B7BB6",
    'cement binder': "#2694CB",
    'mortar': "#B5D5C1",
    'concrete': "#D0E5CA",
    'construction and demolition waste': "#ddd1b6",
}

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, 
                       flow_partition=Partition.Simple('type', list(palette.keys())))

# w1 = weave(sdd, flows, palette=palette).to_widget(**size).auto_save_png('sand_example_v1.png')
Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)
#Sankey.scale = SCALE

#Sankey # Show below
Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

floweaver version: 2.1.0-dev

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")