# Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Wood_Products_Germany_2019_Szichta.xlsx

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Wood_Products_Germany_2019_Szichta.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3684090,1_F_Wood_Products_Germany_2019_Szichta,coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,harvesting of wood,market for harvested wood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
1,3684091,1_F_Wood_Products_Germany_2019_Szichta,non-coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,harvesting of wood,market for harvested wood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
2,3684092,1_F_Wood_Products_Germany_2019_Szichta,bark,"wood, wood waste, and wood products",dry mass,Germany,2019,harvesting of wood,market for harvested wood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
3,3684093,1_F_Wood_Products_Germany_2019_Szichta,coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,import of roundwood,market for harvested wood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
4,3684094,1_F_Wood_Products_Germany_2019_Szichta,non-coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,import of roundwood,market for harvested wood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
5,3684095,1_F_Wood_Products_Germany_2019_Szichta,coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,market for harvested wood,export of roundwood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
6,3684096,1_F_Wood_Products_Germany_2019_Szichta,non-coniferous wood,"wood, wood waste, and wood products",dry mass,Germany,2019,market for harvested wood,export of roundwood,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
7,3684097,1_F_Wood_Products_Germany_2019_Szichta,roundwood,"wood, wood waste, and wood products",dry mass,Germany,2019,market for harvested wood,"use of roundwood, unspecified",History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
8,3684098,1_F_Wood_Products_Germany_2019_Szichta,roundwood,"wood, wood waste, and wood products",dry mass,Germany,2019,market for harvested wood,sawmill industry,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
9,3684099,1_F_Wood_Products_Germany_2019_Szichta,"wood products, semi-finished","wood, wood waste, and wood products",dry mass,Germany,2019,sawmill industry,production of final products and commodities,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
10,3684100,1_F_Wood_Products_Germany_2019_Szichta,"wood products, semi-finished","wood, wood waste, and wood products",dry mass,Germany,2019,import of semi-finished products,production of final products and commodities,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
11,3684101,1_F_Wood_Products_Germany_2019_Szichta,"wood products, semi-finished","wood, wood waste, and wood products",dry mass,Germany,2019,production of final products and commodities,export of semi-finished products,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
12,3684102,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,production of final products and commodities,market for finished products,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
13,3684103,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,import of finished products,market for finished products,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
14,3684104,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for finished products,export of finished products,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
15,3684105,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for finished products,use phase - construction,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
16,3684106,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for finished products,use phase - furniture,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
17,3684107,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for finished products,use phase - paper and packaging,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
18,3684108,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for finished products,use phase - other,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
19,3684109,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,use phase - construction,use phase,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
20,3684110,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,use phase - furniture,use phase,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
21,3684111,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,use phase - paper and packaging,use phase,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
22,3684112,1_F_Wood_Products_Germany_2019_Szichta,wood products,"wood, wood waste, and wood products",dry mass,Germany,2019,use phase - other,use phase,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
23,3684113,1_F_Wood_Products_Germany_2019_Szichta,wood waste,"wood, wood waste, and wood products",dry mass,Germany,2019,use phase,treatment of industrial waste,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
24,3684114,1_F_Wood_Products_Germany_2019_Szichta,"wood, recovered","wood, wood waste, and wood products",dry mass,Germany,2019,use phase,"use of recovered wood, unspecified",History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
25,3684115,1_F_Wood_Products_Germany_2019_Szichta,"wood, recovered","wood, wood waste, and wood products",dry mass,Germany,2019,use phase,sawmill industry,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
26,3684116,1_F_Wood_Products_Germany_2019_Szichta,"wood products, semi-finished","wood, wood waste, and wood products",dry mass,Germany,2019,sawmill industry,sawmill industry,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
27,3684117,1_F_Wood_Products_Germany_2019_Szichta,production residue,"wood, wood waste, and wood products",dry mass,Germany,2019,sawmill industry,market for sawmill byproducts,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
28,3684118,1_F_Wood_Products_Germany_2019_Szichta,production residue,"wood, wood waste, and wood products",dry mass,Germany,2019,production of final products and commodities,market for sawmill byproducts,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
29,3684119,1_F_Wood_Products_Germany_2019_Szichta,sawmill by-products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for sawmill byproducts,sawmill industry,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN
30,3684120,1_F_Wood_Products_Germany_2019_Szichta,sawmill by-products,"wood, wood waste, and wood products",dry mass,Germany,2019,market for sawmill byproducts,use of sawmill by-products and industrial resi...,History,...,Mm3_SWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_SWE stands for million cubic meters o...,NaN,NaN,NaN

In [5]:
import pandas as pd
flows       = pd.read_excel('1_F_Wood_Products_Germany_2019_Szichta.xlsx','Data')
material    = 'wood, wood waste, and wood products'
layer       = 'dry mass'
region      = 'Germany'
scenario    = 'History'
time        = 2019

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,harvesting of wood,market for harvested wood,coniferous wood,46.80
1,harvesting of wood,market for harvested wood,non-coniferous wood,6.70
2,harvesting of wood,market for harvested wood,bark,0.24
3,import of roundwood,market for harvested wood,coniferous wood,6.90
4,import of roundwood,market for harvested wood,non-coniferous wood,0.70
5,market for harvested wood,export of roundwood,coniferous wood,7.30
6,market for harvested wood,export of roundwood,non-coniferous wood,1.50
7,market for harvested wood,"use of roundwood, unspecified",roundwood,0.88
8,market for harvested wood,sawmill industry,roundwood,51.66
9,sawmill industry,production of final products and commodities,"wood products, semi-finished",41.29
10,import of semi-finished products,production of final products and commodities,"wood products, semi-finished",12.61
11,production of final products and commodities,export of semi-finished products,"wood products, semi-finished",21.42
12,production of final products and commodities,market for finished products,wood products,28.63
13,import of finished products,market for finished products,wood products,8.41
14,market for finished products,export of finished products,wood products,5.70
15,market for finished products,use phase - construction,wood products,19.46
16,market for finished products,use phase - furniture,wood products,6.97
17,market for finished products,use phase - paper and packaging,wood products,4.07
18,market for finished products,use phase - other,wood products,0.85
19,use phase - construction,use phase,wood products,19.46
20,use phase - furniture,use phase,wood products,6.97
21,use phase - paper and packaging,use phase,wood products,4.07
22,use phase - other,use phase,wood products,0.85
23,use phase,treatment of industrial waste,wood waste,2.00
24,use phase,"use of recovered wood, unspecified","wood, recovered",11.74
25,use phase,sawmill industry,"wood, recovered",1.32
26,sawmill industry,sawmill industry,"wood products, semi-finished",3.73
27,sawmill industry,market for sawmill byproducts,production residue,17.15
28,production of final products and commodities,market for sawmill byproducts,production residue,3.85
29,market for sawmill byproducts,sawmill industry,sawmill by-products,5.50
30,market for sawmill byproducts,use of sawmill by-products and industrial resi...,sawmill by-products,15.50

In [6]:
from floweaver import *
import pandas as pd
Sankey_version = '1_F_Wood_Products_Germany_2019_Szichta'

# Define the processes
nodes = {
    'harvesting of wood': ProcessGroup(['harvesting of wood'], title='harvesting of wood'),
    'import of roundwood': ProcessGroup(['import of roundwood'], title='import of roundwood'),
    'export of roundwood': ProcessGroup(['export of roundwood'], title='export of roundwood'),
    'use of roundwood, unspecified': ProcessGroup(['use of roundwood, unspecified'], title='use of roundwood, unspecified'),
    'market for harvested wood': ProcessGroup(['market for harvested wood'], title='market for harvested wood'),
    'sawmill industry': ProcessGroup(['sawmill industry'], title='sawmill industry'),
    'production of final products and commodities': ProcessGroup(['production of final products and commodities'], title='final production'),
    'import of semi-finished products': ProcessGroup(['import of semi-finished products'], title='imports'),
    "export of semi-finished products": ProcessGroup(["export of semi-finished products"],title='exports'),
    'market for finished products': ProcessGroup(['market for finished products'], title='market for finished products'),
    "import of finished products": ProcessGroup(["import of finished products"],title='imports'),
    'export of finished products': ProcessGroup(['export of finished products'], title='exports'),
    'use phase - construction': ProcessGroup(['use phase - construction'], title='use phase - construction'),
    'use phase - furniture': ProcessGroup(['use phase - furniture'], title='use phase - furniture'),
    'use phase - paper and packaging': ProcessGroup(['use phase - paper and packaging'], title='use phase - paper and packaging'),
    'use phase - other': ProcessGroup(['use phase - other'], title='use phase - other'),
    'use phase': ProcessGroup(['use phase'], title='use phase'),
    'use of recovered wood, unspecified': ProcessGroup(['use of recovered wood, unspecified'], title='use of recovered wood, unspecified'),
    'treatment of industrial waste': ProcessGroup(['treatment of industrial waste'], title='treatment of industrial waste'),
    'market for sawmill byproducts': ProcessGroup(['market for sawmill byproducts'], title='market for sawmill byproducts'),
    'use of sawmill by-products and industrial residues, unspecified': ProcessGroup(['use of sawmill by-products and industrial residues, unspecified'], title='use of sawmill by-products and industrial residues, unspecified'),
    "loop1": Waypoint(title='', direction='L'),
    "loop2": Waypoint(title='', direction='L'),    
    "loop3": Waypoint(title='', direction='L'),
    "forward1": Waypoint(title='', direction='R'),    
}

# Define flows
bundles = [
    Bundle('import of roundwood', 'market for harvested wood'),
    Bundle('harvesting of wood', 'market for harvested wood'),
    Bundle('market for harvested wood', 'use of roundwood, unspecified'),
    Bundle('market for harvested wood', 'sawmill industry'),
    Bundle('market for harvested wood', 'export of roundwood'),
    Bundle('sawmill industry','production of final products and commodities'),
    Bundle('sawmill industry', 'market for sawmill byproducts', waypoints=['forward1']),
    Bundle('import of semi-finished products','production of final products and commodities'),
    Bundle('production of final products and commodities','export of semi-finished products'),
    Bundle('production of final products and commodities', 'market for finished products'),  
    Bundle('production of final products and commodities', 'market for sawmill byproducts'),
    Bundle('import of finished products', 'market for finished products'), 
    Bundle('market for finished products', 'export of finished products'),    
    Bundle('market for finished products', 'use phase - construction'),
    Bundle('market for finished products', 'use phase - furniture'),
    Bundle('market for finished products', 'use phase - paper and packaging'),
    Bundle('market for finished products', 'use phase - other'),
    Bundle('use phase - construction', 'use phase'),
    Bundle('use phase - furniture', 'use phase'),
    Bundle('use phase - paper and packaging', 'use phase'),
    Bundle('use phase - other', 'use phase'),
    Bundle('use phase', 'treatment of industrial waste'),
    Bundle('use phase', 'use of recovered wood, unspecified'),
    Bundle('use phase', 'sawmill industry', waypoints=['loop2']),
    Bundle('sawmill industry', 'sawmill industry', waypoints=['loop1'], flow_selection='type == "wood products, semi-finished"'), 
    Bundle('market for sawmill byproducts', 'use of sawmill by-products and industrial residues, unspecified'),    
    Bundle('market for sawmill byproducts', 'sawmill industry', waypoints=['loop3']),
]

# Set the colours for the labels in the partition.
palette = {
    'coniferous wood': 'lightgreen',
    'non-coniferous wood': 'olivedrab',
    'bark': 'darkgoldenrod',
    'roundwood': 'yellowgreen',
    'sawmill by-products': 'lightgrey',
    'wood products, semi-finished': 'wheat',
    'wood products': 'lightblue',
    'wood waste': 'tan',
    'production residue': 'silver',
    'wood, recovered': 'tan',
}

#Define the ordering of the processes and waypoints
ordering = [
    [["import of roundwood"],["harvesting of wood"],[],[],[]],
    [[],["market for harvested wood"],[],[],[]],
    [["import of semi-finished products"],["sawmill industry",'loop1'],['export of roundwood'],[],['use of roundwood, unspecified']],
    [["import of finished products"],["production of final products and commodities"],['forward1'],[],[]],
    [[],['market for finished products'],['market for sawmill byproducts'],['loop3'],['export of semi-finished products']],
    [[],['use phase - construction','use phase - furniture','use phase - paper and packaging','use phase - other'],[],[],['export of finished products']],
    [[],['use phase'],[],['loop2'],['use of sawmill by-products and industrial residues, unspecified']],
    [[],['use of recovered wood, unspecified'],['treatment of industrial waste'],[],[]],
]

# Generate the Sankey diagram
size = dict(width=1400, height=400)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=Partition.Simple('type', list(palette.keys())))

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [7]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

KeyError: 'pop from an empty set'

In [ ]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")