## Configuration and test of floweaver Sankey(s) for IEDC dataset 1_F_Wood_Products_Balance_Germany_1950_2025_Thuenen

In [1]:
import pandas as pd
flows = pd.read_excel('1_F_Wood_Products_Balance_Germany_1950_2025_Thuenen.xlsx','Data') # Insert filename of IEDC download
flows

,id,dataset_name,aspect 1 : commodity,aspect 2 : material,aspect 3 : layer,aspect 4 : region,aspect 5 : time,aspect 6 : origin_process,aspect 7 : destination_process,aspect 8 : scenario,...,unitcode,unitcode1,stats_array_1,stats_array_2,stats_array_3,stats_array_4,comment,reserve1,reserve2,reserve3
0,3684277,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,roundwood,wood and wood products,dry mass,Germany,1950,forestry,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
1,3684278,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,"wood, recycled",wood and wood products,dry mass,Germany,1950,waste management,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
2,3684279,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,recovered paper,wood and wood products,dry mass,Germany,1950,waste management,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
3,3684280,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,1950,import of wood and wood products,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
4,3684281,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,1950,stock decrease,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,3684880,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,2025,import of wood and wood products,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
604,3684881,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,2025,stock decrease,domestic market for wood and all wood products...,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
605,3684882,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,2025,domestic market for wood and all wood products...,domestic consumption,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
606,3684883,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,2025,domestic market for wood and all wood products...,export of wood and wood products,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN
607,3684884,1_F_Wood_Products_Balance_Germany_1950_2025_Th...,wood and wood products,wood and wood products,dry mass,Germany,2025,domestic market for wood and all wood products...,stock increase,History,...,Mm3_RWE,yr,NaN,NaN,NaN,NaN,Unit Mm3_RWE stands for million m³(roundwood e...,NaN,NaN,NaN

In [2]:
import pandas as pd
flows       = pd.read_excel('1_F_Wood_Products_Balance_Germany_1950_2025_Thuenen.xlsx','Data')
material    = 'wood and wood products'
layer       = 'dry mass'
region      = 'Germany'
scenario    = 'History'
time        =  2015

ExtractData = flows.loc[(flows['aspect 2 : material'] == material) & (flows['aspect 3 : layer'] == layer) & (flows['aspect 4 : region'] == region) & (flows['aspect 8 : scenario'] == scenario) & (flows['aspect 5 : time'] == time)]
SankeyDatar = ExtractData.drop(columns=['id','dataset_name','aspect 2 : material','aspect 3 : layer','aspect 4 : region','aspect 8 : scenario','aspect 5 : time','aspect 9 : ','aspect 10 : ','aspect 11 : ','aspect 12 : ','unitcode','unitcode1','stats_array_1','stats_array_2','stats_array_3','stats_array_4','comment','reserve1','reserve2','reserve3'])
SankeyDatar.rename(columns={'aspect 6 : origin_process': 'source', 'aspect 7 : destination_process': 'target','aspect 1 : commodity': 'type'}, inplace=True)
column_names= ['source','target','type','value']
SankeyDatar = SankeyDatar.reindex(columns=column_names)
SankeyDatar.reset_index(drop=True, inplace=True)
SankeyDatar

,source,target,type,value
0,forestry,domestic market for wood and all wood products...,roundwood,70.190891
1,waste management,domestic market for wood and all wood products...,"wood, recycled",10.715100
2,waste management,domestic market for wood and all wood products...,recovered paper,44.544606
3,import of wood and wood products,domestic market for wood and all wood products...,wood and wood products,133.024643
4,stock decrease,domestic market for wood and all wood products...,wood and wood products,0.000000
5,domestic market for wood and all wood products...,domestic consumption,wood and wood products,132.405565
6,domestic market for wood and all wood products...,export of wood and wood products,wood and wood products,124.252040
7,domestic market for wood and all wood products...,stock increase,wood and wood products,1.817636

In [3]:
from floweaver import *

Sankey_version = '1_F_Wood_Products_Balance_Germany_1950_2025_Thuenen'

# Define the nodes
nodes = {
    'forestry': ProcessGroup(['forestry'], title='forestry'),
    'waste management': ProcessGroup(['waste management'], title='waste management'),
    'import of wood and wood products': ProcessGroup(['import of wood and wood products'], title='imports'),  
    'stock decrease': ProcessGroup(['stock decrease'], title='stock decrease'),
    'domestic market for wood and all wood products, aggregated': ProcessGroup(['domestic market for wood and all wood products, aggregated'], title='domestic market for wood and all wood products, aggregated'),
    'export of wood and wood products': ProcessGroup(['export of wood and wood products'], title='exports'),
    'domestic consumption': ProcessGroup(['domestic consumption'], title='domestic consumption'),
    'stock increase': ProcessGroup(['stock increase'], title='stock increase'),
}
# Define the bundles
bundles = [
    Bundle('forestry', 'domestic market for wood and all wood products, aggregated'),
    Bundle('import of wood and wood products', 'domestic market for wood and all wood products, aggregated'),
    Bundle('waste management', 'domestic market for wood and all wood products, aggregated'),
    Bundle('stock decrease', 'domestic market for wood and all wood products, aggregated'),
    Bundle('domestic market for wood and all wood products, aggregated', 'export of wood and wood products'),
    Bundle('domestic market for wood and all wood products, aggregated', 'domestic consumption'),
    Bundle('domestic market for wood and all wood products, aggregated', 'stock increase'),
]

# Define the ordering
ordering = [
[['import of wood and wood products'],['forestry'],['waste management'],['stock decrease']],
[[],['domestic market for wood and all wood products, aggregated'],[]],
[['export of wood and wood products'],['domestic consumption'],[],['stock increase'],],
]

flows_by_type = Partition.Simple('type', ['roundwood','wood, recycled','recovered paper','wood and wood products'])

palette = {
    'roundwood':                         'olivedrab',
    'wood, recycled':                    'firebrick',
    'recovered paper':                   'teal',
    'wood and wood products':            'gold',
}

# Generate the Sankey diagram
size = dict(width=1200, height=300)

# New SDD with the flow_partition set
sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)

Sankey = weave(sdd, SankeyDatar, palette=palette).to_widget(**size)

Sankey # Show below

Sankey.auto_save_png(Sankey_version + '_' + region + '_' + str(time) + '.png')
Sankey.auto_save_svg(Sankey_version + '_' + region + '_' + str(time) + '.svg')

In [4]:
# double-check and export Sankey specification as .json
if isinstance(SankeyDatar, pd.DataFrame):
    SankeyDatar = Dataset(SankeyDatar)
    
spec = compile_sankey_definition(
    sdd,       # see above: sdd = SankeyDefinition(nodes, bundles, ordering, flow_partition=flows_by_type)
    measures   = "value",
    link_width = None,
    link_color = None,
    palette    = palette,
    add_elsewhere_waypoints = True,
    dimension_tables        = None,
)

Sankey = execute_weave(spec, SankeyDatar)
Sankey.to_widget(**size)

In [5]:
# export Sankey spec as .json for use in IEDC web application
import json
json_data = json.dumps(spec.to_json(), indent=2)
# Write Sankey spec to .json, filename as indicated in: 
# https://github.com/IndEcol/IEDC_floweaver_integration/blob/main/floweaver_IEDC_Sankey_configs/floweaver_IEDC_Sankey_configs.config
with open(Sankey_version + '.json', "w", encoding="utf-8") as f:
    f.write(json_data)
    f.write("\n")